### ISSUE TITLE
作者。这个如果我有3条数据 设置了大于等于4条才会滚动, 但是页面上显示了6条 ，有没有什么办法 如果我的数据没有大于4条，页面是显示当前有的3条，谢谢

### ISSUE THREAD

**Issue by baibaiIloveyou** [xfy520/vue3-seamless-scroll#10]

**Comment by xfy520** [comment]
好的，我晚上回去处理下

**Comment by saburo-super** [comment]
这是一个bug 如果: list 的数据是后面加载出来的时候就不行 ，就是说如果 onMounted给那个list 赋值，还是不滚动 ，如果初期定义list 的时候有数据才行

**Comment by qbh990803** [comment]
我也遇到了这个问题，现在的解决办法是自己手动判断数据是否大于limitScrollNum,如果是则用vue3-seamless-scroll，不是的话则就正常渲染。

**Comment by xfy520** [comment]
好的，由于最近在忙，我周末解决一些，谢谢支持

**Comment by xfy520** [comment]
已修复，感谢支持

**Comment by wolaishishihuo** [comment]
这个bug修复了么  我还是有这个问题
