### ISSUE TITLE
[error] update from 1.1.5 to 1.2.0

### ISSUE THREAD

**Issue by coderzhaoziwei** [xfy520/vue3-seamless-scroll#14]
我的项目以前安装的是 1.1.5 版本的，今天项目打包的时候自动更新到了 1.2.0，出现了滚动区域渲染失败的情况。

页面区域空白，控制台报了一连串 Vue 的 warning。

具体问题我暂时没时间去看，直接切回 1.1.5 版本并锁定之后，就正常了。

最后，感谢作者的项目让我提高了搬砖的效率。

**Comment by xfy520** [comment]
好的，由于最近在忙，我周末解决一些，谢谢支持

**Comment by xfy520** [comment]
感谢支持、已升级
