### ISSUE TITLE
高度如果是动态的，好像就有问题了，内部也没有暴露reset方法

### ISSUE THREAD

**Issue by lykl** [xfy520/vue3-seamless-scroll#15]

**Comment by xfy520** [comment]
感谢支持，我这边抽空解决一下

**Comment by orignFizz** [comment]
<template v-if="list.length > 0">
      <vue3-seamless-scroll
        :list="list"
        class="scroll"
        hover
        :step="0.2"
        :isWatch="true"
      >
        <div v-for="(item, index) in list" :key="index" class="table-item">
          <div class="table-item-cell">{{ item.tableName }}</div>
          <div class="table-item-cell">{{ item.createTime }}</div>
          <div class="table-item-cell">{{ item.createBy }}</div>
        </div>
      </vue3-seamless-scroll>
    </template>
我测试过了，可以的

**Comment by xfy520** [comment]
已暴露Reset方法
