### ISSUE TITLE
新增数据后, 比如数据从1-5个 添加到6个, 滚动会到第五个卡顿 跳一下

### ISSUE THREAD

**Issue by wolaishishihuo** [xfy520/vue3-seamless-scroll#16]
新增数据后, 比如数据从1-5个 添加到6个, 滚动会到第五个卡顿 跳一下, 这个如何解决呀, 目前加了copynum, 也是会有跳一下, 现在是加了个 定时器, 5分钟数据不变,就刷新一下组件.  还有其他方法么?

**Comment by xfy520** [comment]
感谢支持、已修复
