### ISSUE TITLE
安装不了，yarn也试了，在VBEN的群中知道的该项目； 我现在也是在VBEN中使用，用不了

### ISSUE THREAD

**Issue by fkuepl** [xfy520/vue3-seamless-scroll#2]
![image](https://user-images.githubusercontent.com/2612446/124584610-09206000-de87-11eb-81d2-266a64aa8a5c.png)

**Comment by fkuepl** [comment]
是要降版本吗？

**Comment by xfy520** [comment]
![image](https://user-images.githubusercontent.com/78788091/124692272-de2e1e80-df0f-11eb-9c4d-dcd2277a88b2.png)

首先感谢支持，我这边这个命令可以安装，具体能截一下完整的安装报错图吗？

**Comment by xfy520** [comment]
![image](https://user-images.githubusercontent.com/78788091/124694791-880faa00-df14-11eb-8fc8-7ebeddb8de4a.png)

我这边在这个项目下用yarn add vue3-seamless-scroll也没有问题

**Comment by fkuepl** [comment]
![image](https://user-images.githubusercontent.com/2612446/124702097-62899d00-df22-11eb-9343-0af09427bee8.png)
![image](https://user-images.githubusercontent.com/2612446/124702121-70d7b900-df22-11eb-9eb8-b9574021faa1.png)

**Comment by xfy520** [comment]
@fkuepl 这个问题可能不是我这个组件引起的，你单独运行这个项目试试，我感觉这个项目运行有问题，如果单独运行没问题引入这个组件就有问题那就有可能是vue版本问题，这个组件vue最低版本要求3.0.3以上。

**Comment by woodsZero** [comment]
我把之前的依赖删除了，重新下载依赖可以

**Comment by fkuepl** [comment]
好吧，那可能是我这里的问题
