### ISSUE TITLE
鼠标悬浮停止后，加入手动滚动。

### ISSUE THREAD

**Issue by mmmmReed** [xfy520/vue3-seamless-scroll#8]
大大好，您的这个插件很方便好用，只是产品想要鼠标悬浮滚动停止后还能鼠标滑轮滚动。目前没有想到什么思路去再加入手动滚动。想请教下，能否在使用您的插件的情况下，再去实现这个功能。如果不行的话，之后只能参考您的源码在封装一个组件了。

**Comment by xfy520** [comment]
您好，我这边晚上回去看能不能在原有基础上添加，感谢支持

**Comment by mmmmReed** [comment]
好的，期待，谢谢您

**Comment by xfy520** [comment]
您好，手动滚动添加wheel参数支持

**Comment by mmmmReed** [comment]
非常感谢，我上周已经按照您的代码封装了滚轮滚动功能，现在再参考下您的源码，看看我的思路和整体做法和您的有没有出入。我会在博客里向别人推荐您的插件的。

**Comment by xfy520** [comment]
感谢支持
