### ISSUE TITLE
左右滚动的时候好像有点问题

### ISSUE THREAD

**Issue by EndureBlaze** [xfy520/vue3-seamless-scroll#9]
对应组件的代码如下，图片都是同一张

```vue
<script setup lang="ts">
import util from '@/common/utils/util'
import { Vue3SeamlessScroll } from 'vue3-seamless-scroll'

let data = [
  util.getImg('icon.svg'),
  util.getImg('icon.svg'),
  util.getImg('icon.svg'),
  util.getImg('icon.svg'),
  util.getImg('icon.svg'),
  util.getImg('icon.svg'),
]
</script>
<template>
  <div>
    <div class="knight-scroll">
      <vue3-seamless-scroll :list="data" direction="left">
        <span
          ><img v-for="(item, index) in data" :src="item" :key="index" /> </span
      ></vue3-seamless-scroll>
    </div>
  </div>
</template>
<style scoped lang="scss">
.knight-scroll {
  background-color: black;
  overflow: hidden;
  width: 100%;
}

img {
  margin-left: 50px;
}
</style>

```

出来的效果是这样的，是不是我哪里设置错了
<img width="1435" alt="图片" src="https://user-images.githubusercontent.com/25337480/159893583-11399530-e219-4405-b183-4c58a68e6489.png">

这样确实会滚动，但是和我想的差别有点大哈哈

**Comment by xfy520** [comment]
您好，因为父div要设置高度跟宽度，你这里没有设置高度导致子img会撑开高度。

```html
<script setup lang="ts">
import util from '@/common/utils/util'
import { Vue3SeamlessScroll } from 'vue3-seamless-scroll'

let data = [
  util.getImg('icon.svg'),
  util.getImg('icon.svg'),
  util.getImg('icon.svg'),
  util.getImg('icon.svg'),
  util.getImg('icon.svg'),
  util.getImg('icon.svg'),
]
</script>
<template>
  <div>
    <div class="knight-scroll">
      <vue3-seamless-scroll :list="data" direction="left">
         <img v-for="(item, index) in data" :src="item" :key="index" />
       </vue3-seamless-scroll>
    </div>
  </div>
</template>
<style scoped lang="scss">
.knight-scroll {
  background-color: black;
  width: 720px;
  height: 50px;
  overflow: hidden;
}

img {
  margin-left: 50px;
  height: 50px;
  width: 50px;
}
</style>
```

这里的高度50px你可以自己根据图片的真实高度、宽度设置合适宽度

**Comment by EndureBlaze** [comment]
@xfy520 十分感谢！我明天去公司再尝试一下。

**Comment by EndureBlaze** [comment]
@xfy520 我这里把图片和外部容器的都改成了 80px，好像还是不行
<img width="911" alt="图片" src="https://user-images.githubusercontent.com/25337480/160041812-1b1d2447-c091-4c04-a4fa-fa5a6fc01817.png">

样式是这样

```css
.knight-scroll {
  background-color: black;
  height: 80px;
  width: 500px;
  overflow: hidden;
}

img {
  height: 80px;
  width: 80px;
  margin-left: 50px;
}
```

理论上不应该在第二行了

**Comment by EndureBlaze** [comment]
我重新刷新了之后好像可以了，奇怪，为什么第二次刷新才好

**Comment by xfy520** [comment]
好的，到时候我看看是不是bug

**Comment by EndureBlaze** [comment]
另外还有页面比较复杂的时候会发生不滚动的情况，需要切换到其他页面再回来才能滚动

https://user-images.githubusercontent.com/25337480/160558800-f5ec3b96-d446-4d70-b8ef-2500d26e5fc9.mp4

似乎是 JS 部分没有生效？

**Comment by EndureBlaze** [comment]
仓库的话是这个 https://github.com/EndureBlazePages/test_page，这里使用了滚动 https://github.com/EndureBlazePages/test_page/blob/3e8addaaa72602d8f00a5523c71d33c732781b55/src/page/home/introduce.vue#L31

**Comment by EndureBlaze** [comment]
> 好的，到时候我看看是不是bug

我试了下，如果左右滚动的实时候我想单行的话加上 flex 就好了，但是我不知道怎么注入这个属性

https://user-images.githubusercontent.com/25337480/161376444-8ba47c89-dac5-447b-a3dd-f038286bcf4b.mov

**Comment by EndureBlaze** [comment]
我尝试添加了一下注入的部分 https://github.com/xfy520/vue3-seamless-scroll/pull/11 本地写了一个测试应该没问题，不过我的 ESLint 好像影响了你的代码规范。。。介意的话可以只看 [这部分](https://github.com/EndureBlaze/vue3-seamless-scroll/blob/589731931b8b965fdb95bae6866ec69675edda7d/package/Vue3SeamlessScroll.tsx#L96) 还有 [这里](https://github.com/EndureBlaze/vue3-seamless-scroll/blob/589731931b8b965fdb95bae6866ec69675edda7d/package/Vue3SeamlessScroll.tsx#L182) （[另外一处修改](https://github.com/EndureBlaze/vue3-seamless-scroll/blob/589731931b8b965fdb95bae6866ec69675edda7d/package/Vue3SeamlessScroll.tsx#L195)）吧 ，没有怎么写过 tsx，可能这个不是最优的写法，我只是提供一种思路
